### ISSUE TITLE
整合包优化和问题反馈

### ISSUE THREAD

**Issue by TianXij** [gengyoubo/LA#2]
模组我稍微对了一下，那个饰品栏可以不用删。部分模组的物品可以放的饰品栏。可以节省空间，然后操作相对舒心一些。如果觉得过空的话，可以添加一个更多饰品模组。冒险方面建议删除吸血鬼和狼人两个模组。原因嘛因为有科技要素。所以大部分时间基本都宅在一个地方跑科技。基本体验不到这两个模组的内容。而且相对于攀科技来说，这两个模组对实力的提升太少了。没啥子成就感。如果想增加冒险方面元素的话，可以尝试添加Dungeon Crawl或Wesley的冒险地牢模组。不过我不建议两个都加，毕竟胶兽模组的实验设施是有地下部分的。如果生成比例没搞好的话。这到处都是地牢，有点难绷。

**Comment by TianXij** [comment]
科技向方面建议添加封包合成，减少肝度。如果要拉长科技线的话，可以增加龙之进化。加龙之进化的话，封包也要加哦。星辉和植物魔法这两个是备选项。因为像这两个的话一定要搞模块化建筑的。因为星能液和魔力产量实在是太低了。考虑到你这个版本，只能算是备选了。也可以加个支线上太空。Ad Astra!模组可以实现。虽然只有几颗星球。
模组建议删除精致存储和其附属。因为有等价交换的存在。他和ae2基本属于是同时可以同时攀的。哪怕把压印器改掉了，ae2走机械动力爬的速度也挺快的。毕竟机械动力只要做出第1个精密构件，后面的基本都可以加速了。爬得很快。就导致精致存储，食之无味，弃之可惜了。

**Comment by TianXij** [comment]
休闲项方面我说的一些模组，如果加了的话，会相当破坏平衡。但是考虑到等价交换这个极端。似乎其他的都挺平衡的。
车万女仆老生常谈了。永恒枪械工坊也是老生常谈了。只要枪的伤害够，我想没人愿意放下他吧。毕竟太舒服了。如果以后要升级版本的话，可以尝试永恒枪械工坊零。
剩下的想起来再说吧。

**Comment by gengyoubo** [comment]
> 模组我稍微对了一下，那个饰品栏可以不用删。部分模组的物品可以放的饰品栏。可以节省空间，然后操作相对舒心一些。如果觉得过空的话，可以添加一个更多饰品模组。冒险方面建议删除吸血鬼和狼人两个模组。原因嘛因为有科技要素。所以大部分时间基本都宅在一个地方跑科技。基本体验不到这两个模组的内容。而且相对于攀科技来说，这两个模组对实力的提升太少了。没啥子成就感。如果想增加冒险方面元素的话，可以尝试添加Dungeon Crawl或Wesley的冒险地牢模组。不过我不建议两个都加，毕竟胶兽模组的实验设施是有地下部分的。如果生成比例没搞好的话。这到处都是地牢，有点难绷。

万一有人玩狼人和吸血鬼呢？

**Comment by gengyoubo** [comment]
> 科技向方面建议添加封包合成，减少肝度。如果要拉长科技线的话，可以增加龙之进化。加龙之进化的话，封包也要加哦。星辉和植物魔法这两个是备选项。因为像这两个的话一定要搞模块化建筑的。因为星能液和魔力产量实在是太低了。考虑到你这个版本，只能算是备选了。也可以加个支线上太空。Ad Astra!模组可以实现。虽然只有几颗星球。
> 
> 模组建议删除精致存储和其附属。因为有等价交换的存在。他和ae2基本属于是同时可以同时攀的。哪怕把压印器改掉了，ae2走机械动力爬的速度也挺快的。毕竟机械动力只要做出第1个精密构件，后面的基本都可以加速了。爬得很快。就导致精致存储，食之无味，弃之可惜了。

龙之进化的话就别想了，这个模组在新版优化很差。植物魔法的话我会考虑考虑。精致的话我收集一点意见我在考虑一下。

**Comment by gengyoubo** [comment]
> 休闲项方面我说的一些模组，如果加了的话，会相当破坏平衡。但是考虑到等价交换这个极端。似乎其他的都挺平衡的。
> 
> 车万女仆老生常谈了。永恒枪械工坊也是老生常谈了。只要枪的伤害够，我想没人愿意放下他吧。毕竟太舒服了。如果以后要升级版本的话，可以尝试永恒枪械工坊零。
> 
> 剩下的想起来再说吧。

这个我也会考虑一下

**Comment by gengyoubo** [comment]
> 科技向方面建议添加封包合成，减少肝度。如果要拉长科技线的话，可以增加龙之进化。加龙之进化的话，封包也要加哦。星辉和植物魔法这两个是备选项。因为像这两个的话一定要搞模块化建筑的。因为星能液和魔力产量实在是太低了。考虑到你这个版本，只能算是备选了。也可以加个支线上太空。Ad Astra!模组可以实现。虽然只有几颗星球。
> 
> 模组建议删除精致存储和其附属。因为有等价交换的存在。他和ae2基本属于是同时可以同时攀的。哪怕把压印器改掉了，ae2走机械动力爬的速度也挺快的。毕竟机械动力只要做出第1个精密构件，后面的基本都可以加速了。爬得很快。就导致精致存储，食之无味，弃之可惜了。

那个星球模组似乎是1.19.X或者是1.20.X的模组

**Comment by TianXij** [comment]
> > 模组我稍微对了一下，那个饰品栏可以不用删。 部分模组的物品可以放的饰品栏。 可以节省空间，然后操作相对舒心一些。 如果觉得过空的话，可以添加一个更多饰品模组。 冒险方面建议删除吸血鬼和狼人两个模组。 原因嘛因为有科技要素。 所以大部分时间基本都宅在一个地方跑科技。 基本体验不到这两个模组的内容。 而且相对于攀科技来说，这两个模组对实力的提升太少了。 没啥子成就感。 如果想增加冒险方面元素的话，可以尝试添加Dungeon Crawl或Wesley的冒险地牢模组。 不过我不建议两个都加，毕竟胶兽模组的实验设施是有地下部分的。 如果生成比例没搞好的话。 这到处都是地牢，有点难绷。
> 
> 万一有人玩狼人和吸血鬼呢？

删还是留看你，不过留的话注意解决按键冲突。

**Comment by TianXij** [comment]
> > 科技向方面建议添加封包合成，减少肝度。 如果要拉长科技线的话，可以增加龙之进化。 加龙之进化的话，封包也要加哦。 星辉和植物魔法这两个是备选项。 因为像这两个的话一定要搞模块化建筑的。 因为星能液和魔力产量实在是太低了。 考虑到你这个版本，只能算是备选了。 也可以加个支线上太空。 Ad Astra!模组可以实现。 虽然只有几颗星球。
> > 模组建议删除精致存储和其附属。 因为有等价交换的存在。 他和ae2基本属于是同时可以同时攀的。 哪怕把压印器改掉了，ae2走机械动力爬的速度也挺快的。 毕竟机械动力只要做出第1个精密构件，后面的基本都可以加速了。 爬得很快。 就导致精致存储，食之无味，弃之可惜了。
> 
> 龙之进化的话就别想了，这个模组在新版优化很差。 植物魔法的话我会考虑考虑。 精致的话我收集一点意见我在考虑一下。

植物魔法只适合做支线，毕竟它魔力产量实在是低了。精致考虑到有部分人不会用p2p。应该可以留吧?

**Comment by TianXij** [comment]
> 科技向方面建议添加封包合成，减少肝度。 如果要拉长科技线的话，可以增加龙之进化。 加龙之进化的话，封包也要加哦。 星辉和植物魔法这两个是备选项。 因为像这两个的话一定要搞模块化建筑的。 因为星能液和魔力产量实在是太低了。 考虑到你这个版本，只能算是备选了。 也可以加个支线上太空。 Ad Astra!模组可以实现。 虽然只有几颗星球。 模组建议删除精致存储和其附属。 因为有等价交换的存在。 他和ae2基本属于是同时可以同时攀的。 哪怕把压印器改掉了，ae2走机械动力爬的速度也挺快的。 毕竟机械动力只要做出第1个精密构件，后面的基本都可以加速了。 爬得很快。 就导致精致存储，食之无味，弃之可惜了。

建议添加抽屉，提高单一物品的存储以及做产线收集。 Ae在未有高级的储存单元时，对单一物品储存稍显吃力。
建议添加建筑小帮手,以替换emc饰品中emc建筑之杖的功能。

**Comment by TianXij** [comment]
> > 科技向方面建议添加封包合成，减少肝度。 如果要拉长科技线的话，可以增加龙之进化。 加龙之进化的话，封包也要加哦。 星辉和植物魔法这两个是备选项。 因为像这两个的话一定要搞模块化建筑的。 因为星能液和魔力产量实在是太低了。 考虑到你这个版本，只能算是备选了。 也可以加个支线上太空。 Ad Astra!模组可以实现。 虽然只有几颗星球。 模组建议删除精致存储和其附属。 因为有等价交换的存在。 他和ae2基本属于是同时可以同时攀的。 哪怕把压印器改掉了，ae2走机械动力爬的速度也挺快的。 毕竟机械动力只要做出第1个精密构件，后面的基本都可以加速了。 爬得很快。 就导致精致存储，食之无味，弃之可惜了。
> 
> 建议添加抽屉，提高单一物品的存储以及做产线收集。 Ae在未有高级的储存单元时，对单一物品储存稍显吃力。 建议添加建筑小帮手,以替换emc饰品中emc建筑之杖的功能。

建议添加通量网络满足部分无线电的需求。

**Comment by TianXij** [comment]
> > > 科技向方面建议添加封包合成，减少肝度。 如果要拉长科技线的话，可以增加龙之进化。 加龙之进化的话，封包也要加哦。 星辉和植物魔法这两个是备选项。 因为像这两个的话一定要搞模块化建筑的。 因为星能液和魔力产量实在是太低了。 考虑到你这个版本，只能算是备选了。 也可以加个支线上太空。 Ad Astra!模组可以实现。 虽然只有几颗星球。 模组建议删除精致存储和其附属。 因为有等价交换的存在。 他和ae2基本属于是同时可以同时攀的。 哪怕把压印器改掉了，ae2走机械动力爬的速度也挺快的。 毕竟机械动力只要做出第1个精密构件，后面的基本都可以加速了。 爬得很快。 就导致精致存储，食之无味，弃之可惜了。
> > 
> > 
> > 建议添加抽屉，提高单一物品的存储以及做产线收集。 Ae在未有高级的储存单元时，对单一物品储存稍显吃力。 建议添加建筑小帮手,以替换emc饰品中emc建筑之杖的功能。
> 
> 建议添加通量网络满足部分无线电的需求。

建议添加玉显示信息。

**Comment by gengyoubo** [comment]
添加模组
- [ ] 抽屉模组
- [ ] 建筑小帮手
- [ ] 通用网络
- [ ] 玉显示
- [ ] 封包合成
- [ ] 车万女仆
- [ ] 永恒枪械工坊
- [ ]  生物群系指南针
- [ ] 探险者指南针

**Comment by TianXij** [comment]
> 添加模组
> 
> * [ ]  抽屉模组
> * [ ]  建筑小帮手
> * [ ]  通用网络
> * [ ]  玉显示
> * [ ]  封包合成
> * [ ]  车万女仆
> * [ ]  永恒枪械工坊
> * [ ]  生物群系指南针
> * [ ]  探险者指南针

**Comment by TianXij** [comment]
模组ae2附加更多存储单元重置版中物品无线连接器。在新世界第1次创建频道时必定出现崩溃。重登后再次创建便不会再出现崩溃的情况。后面有崩溃报告。（不过似乎在某些特殊情况下删除所有频道，重建一个仍会导致崩溃,不过情况似乎过于极端不做考量。)
[minecraft-exported-crash-info-2024-06-14T00-18-11.zip](https://github.com/user-attachments/files/15825528/minecraft-exported-crash-info-2024-06-14T00-18-11.zip)
这个bug影响不是很大，但是还是有点影响游戏体验的。如果修不了的话就算了，到时候ftp任务里面说一句。不过物品还是不要禁用了，毕竟对科技项的影响还真挺大的。有无线和没有无线可以说是两个游戏。

**Comment by gengyoubo** [comment]
估计是放置这个东西发生了空指针，我有时间处理一下。

**Comment by gengyoubo** [comment]
作者估计是没有想到空指针的时候的情况。

**Comment by gengyoubo** [comment]
我先记录一下

**Comment by gengyoubo** [comment]
> 我先记录一下

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2024/6/14 涓婂崍12:18
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at com.the9grounds.aeadditions.client.gui.MEWirelessTransceiverScreen.saveChangesButtonPressed(MEWirelessTransceiverScreen.kt:270) ~[AEAdditions-1.18.2-3.2.8.jar%2359!/:?] {re:classloading}
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.the9grounds.aeadditions.client.gui.MEWirelessTransceiverScreen.m_6375_(MEWirelessTransceiverScreen.kt:153) ~[AEAdditions-1.18.2-3.2.8.jar%2359!/:?] {re:classloading}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:werewolves.mixins.json:client.ScreenMixin,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2345!/:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.18.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by gengyoubo** [comment]
> > 我先记录一下
> 
> ---- Minecraft 崩溃报告 ---- // 对不起，戴夫。
> 
> 时间：2024/6/14 十一月 12:18 描述：mouseClicked 事件处理程序
> 
> java.lang.NullPointerException：mouseClicked 事件处理程序 位于 com.the9grounds.aeadditions.client.gui.MEWirelessTransceiverScreen.saveChangesButtonPressed(MEWirelessTransceiverScreen.kt:270) ~[AEAdditions-1.18.2-3.2.8.jar%2359!/:?] {re:classloading} 位于 net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 位于 net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,re:classloading} 在 net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 在 com.the9grounds.aeadditions.client.gui.MEWirelessTransceiverScreen.m_6375_(MEWirelessTransceiverScreen.kt:153) ~[AEAdditions-1.18.2-3.2.8.jar%2359!/:?] {re:classloading} 在 net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A} 在 net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:werewolves.mixins.json:client.ScreenMixin,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A} 在 net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A} 在 net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 在 net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:mixins.cofhcore.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A} 在 org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10] {} 在 org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2345!/:build 10] {} 在 org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10] {} at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A} at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 在 net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 在 net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23159!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A} 在 jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 在 jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 在 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 在 java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 在 net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.18.jar%2318!/:?] {} 在 cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {} 在 cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {} 在 cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {} 在 cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {} 在 cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {} 在 cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {} 在 cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {} 在 cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
 #4

**Comment by gengyoubo** [comment]
我会重新建一个模组单
